<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Grpc.Net.Client" />
    <PackageReference Include="protobuf-net.Grpc" />
    <PackageReference Include="Ulid" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\NoMercy.NmSystem\NoMercy.NmSystem.csproj" />
  </ItemGroup>
</Project>
