"""List every client-callable hub method in the locked SignalR snapshots.

Run from anywhere in this worktree. Baseline is origin/dev; current is the
checked-in snapshot regenerated by HubContractSnapshotTests in CI.
"""

import json
import subprocess
from pathlib import Path

root = Path(__file__).resolve().parents[1]
baseline_json = subprocess.check_output(
    ["git", "show", "origin/dev:signalr-contracts.json"], cwd=root
)
baseline = json.loads(baseline_json)["hubs"]
current = json.loads((root / "signalr-contracts.json").read_text())["hubs"]
excluded = ("OnConnectedAsync(", "OnDisconnectedAsync(")


def methods_for(snapshot: dict, hub: str) -> dict[str, str]:
    return {
        method: result
        for signature in snapshot[hub]
        if not signature.startswith(excluded)
        for method, result in [signature.split(" -> ", 1)]
    }


def validation(hub: str, method: str, result: str) -> str:
    if hub == "PluginHub" and method.startswith("Send("):
        return "Yes: filter validates id/method; success keeps bool"
    if hub == "RipperHub" and method.startswith("GetDriveState("):
        return "Yes: role/path/known drive; error record"
    if "HubCommandResult" in result:
        return "Yes: result record" if "()" not in method else "No input; result record"
    return "No input; existing data result"


print("| Hub | Method | Before return | After return | Validation/result |")
print("| --- | --- | --- | --- | --- |")
total = 0
command_count = 0
for hub in current:
    before = methods_for(baseline, hub)
    after = methods_for(current, hub)
    if before.keys() != after.keys():
        raise SystemExit(f"Method names or parameters changed in {hub}")
    for method, result in after.items():
        print(
            f"| {hub} | `{method}` | `{before[method]}` | `{result}` | "
            f"{validation(hub, method, result)} |"
        )
        total += 1
        if before[method] in ("System.Threading.Tasks.Task", "System.Void"):
            command_count += 1
        elif hub == "DeviceHub" and method.startswith(("WakeForMusic(", "WakeForVideo(")):
            command_count += 1
        elif hub == "PluginHub" and method.startswith("Send("):
            command_count += 1

print(f"\n{total} callable entries; {command_count} commands; {total - command_count} data queries.")
