import type { AnalyzerRule, Capability, Refusal, Slot } from './contract.js';
import { pascalOf, slugOf } from './contract.js';

export const LICENSE_HEADER: string = [
  '// -----------------------------------------------------------------------------',
  '//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.',
  '//',
  '//  This file is part of NoMercy MediaServer, source-available software (NOT open',
  '//  source). Personal use and contributions are welcome; distribution, resale,',
  '//  relicensing, and commercial exploitation are prohibited without explicit',
  '//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.',
  '//',
  '//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary',
  '// -----------------------------------------------------------------------------',
  '',
  '// Generated by server/nomercy-media-server/tools/plugin-contract. Do not edit.',
  '',
].join('\n');

function trustOf(capability: Capability): string {
  return capability.trust.charAt(0).toUpperCase() + capability.trust.slice(1);
}

function quote(text: string): string {
  return `"${text.replace(/"/g, '\\"')}"`;
}

function descriptorOf(capability: Capability): string {
  const args: string[] = [
    quote(capability.name),
    quote(capability.scope),
    `PluginTrust.${trustOf(capability)}`,
    `${capability.reversible}`,
    quote(capability.facade),
    quote(capability.summary),
    quote(`/nomercy-plugins/capabilities/${slugOf(capability.name)}`),
  ];

  return [
    '        new(',
    ...args.map((argument, index) => `            ${argument}${index < args.length - 1 ? ',' : ''}`),
    '        ),',
  ].join('\n');
}

export function emitCapabilityVocabulary(capabilities: Capability[]): string {
  const rows: string[] = capabilities.map(descriptorOf);

  return [
    LICENSE_HEADER,
    'namespace NoMercy.PluginSdk.Abstractions;',
    '',
    '/// <summary>Every capability a manifest may declare, with its scope, trust floor and facade.</summary>',
    'public static class PluginCapabilityVocabulary',
    '{',
    '    public static IReadOnlyList<PluginCapabilityDescriptor> All { get; } =',
    '    [',
    rows.join('\n'),
    '    ];',
    '',
    '    public static PluginCapabilityDescriptor? ByName(string name)',
    '    {',
    '        return All.FirstOrDefault(capability => capability.Name == name);',
    '    }',
    '}',
    '',
  ].join('\n');
}

export function emitCapabilityNames(capabilities: Capability[]): string {
  const rows: string[] = capabilities.map(
    capability => `    public const string ${pascalOf(capability.name)} = ${quote(capability.name)};`,
  );

  return [
    LICENSE_HEADER,
    'namespace NoMercy.PluginSdk.Abstractions;',
    '',
    '/// <summary>The capability names, so nothing spells one by hand.</summary>',
    'public static class PluginCapabilityNames',
    '{',
    rows.join('\n'),
    '}',
    '',
  ].join('\n');
}

function refusalConstantOf(code: string): string {
  return code
    .replace(/^PLUGIN_/, '')
    .split('_')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1).toLowerCase())
    .join('');
}

function severityOf(refusal: Refusal): string {
  return refusal.severity.charAt(0).toUpperCase() + refusal.severity.slice(1);
}

function refusalDescriptorOf(refusal: Refusal): string {
  const args: string[] = [
    quote(refusal.code),
    `PluginRefusalSeverity.${severityOf(refusal)}`,
    refusal.capability === null ? 'null' : quote(refusal.capability),
    quote(refusal.summary),
  ];

  return [
    '        new(',
    ...args.map((argument, index) => `            ${argument}${index < args.length - 1 ? ',' : ''}`),
    '        ),',
  ].join('\n');
}

export function emitRefusalCodes(refusals: Refusal[]): string {
  const constants: string[] = refusals.map(
    refusal => `    public const string ${refusalConstantOf(refusal.code)} = ${quote(refusal.code)};`,
  );

  return [
    LICENSE_HEADER,
    'namespace NoMercy.PluginSdk.Abstractions;',
    '',
    '/// <summary>Every code a refusal may carry, with its severity and the capability it belongs to.</summary>',
    'public static class PluginRefusalCodes',
    '{',
    constants.join('\n'),
    '',
    '    public static IReadOnlyList<PluginRefusalDescriptor> All { get; } =',
    '    [',
    refusals.map(refusalDescriptorOf).join('\n'),
    '    ];',
    '',
    '    public static PluginRefusalDescriptor? ByCode(string code)',
    '    {',
    '        return All.FirstOrDefault(refusal => refusal.Code == code);',
    '    }',
    '}',
    '',
  ].join('\n');
}

export function emitManifestSchema(schema: unknown, capabilities: Capability[]): string {
  const filled = JSON.parse(JSON.stringify(schema)) as {
    $defs?: { capabilityGrant?: { properties?: { name?: { enum?: string[] } } } };
  };
  const name = filled.$defs?.capabilityGrant?.properties?.name;
  if (name === undefined)
    throw new Error('manifest.schema.json has no $defs.capabilityGrant.properties.name to fill');

  name.enum = capabilities.map(capability => capability.name);

  const body: string[] = JSON.stringify(filled, null, 2)
    .split('\n')
    .map(line => `        ${line}`);

  return [
    LICENSE_HEADER,
    'namespace NoMercy.PluginSdk.Abstractions;',
    '',
    '/// <summary>The schema a plugin.json is read against, with the capability names the server knows.</summary>',
    'public static class PluginManifestSchema',
    '{',
    '    public const string Json = """',
    ...body,
    '        """;',
    '}',
    '',
  ].join('\n');
}

/**
 * The settings schema, as a C# constant.
 *
 * Emitted rather than hand-written for the same reason the manifest schema is:
 * a schema kept in two places is a schema that disagrees with itself, and the
 * half that disagrees is always the one a plugin author reads.
 */
export function emitSettingsSchema(schema: unknown): string {
  const body: string[] = JSON.stringify(schema, null, 2)
    .split('\n')
    .map(line => `        ${line}`);

  return [
    LICENSE_HEADER,
    'namespace NoMercy.PluginSdk.Abstractions;',
    '',
    '/// <summary>The schema a plugin settings declaration is read against.</summary>',
    'public static class PluginSettingsSchema',
    '{',
    '    public const string Json = """',
    ...body,
    '        """;',
    '}',
    '',
  ].join('\n');
}

/**
 * The slot list, as a C# table.
 *
 * A slot a client does not draw is a plugin that vanishes on that client with
 * nothing said, so the list is one source that every platform emits from
 * rather than three lists that drift.
 */
export function emitSlots(slots: Slot[]): string {
  const rows: string[] = slots.map(
    slot =>
      `        new("${slot.kind}", "${slot.slot}", ${JSON.stringify(slot.summary)}),`,
  );

  return [
    LICENSE_HEADER,
    'namespace NoMercy.PluginSdk.Abstractions;',
    '',
    '/// <summary>Where a plugin may place itself, by kind.</summary>',
    '/// <param name="Kind">One of <see cref="PluginKind.All" />.</param>',
    '/// <param name="Slot">The place within that kind.</param>',
    '/// <param name="Summary">What a client draws there.</param>',
    'public sealed record PluginSlotDescriptor(string Kind, string Slot, string Summary);',
    '',
    '/// <summary>Every slot this server knows.</summary>',
    'public static class PluginSlots',
    '{',
    '    public static readonly IReadOnlyList<PluginSlotDescriptor> All =',
    '    [',
    ...rows,
    '    ];',
    '',
    '    /// <summary>Whether this kind can be placed in this slot.</summary>',
    '    public static bool IsKnown(string kind, string slot) =>',
    '        All.Any(descriptor =>',
    '            string.Equals(descriptor.Kind, kind, StringComparison.Ordinal)',
    '            && string.Equals(descriptor.Slot, slot, StringComparison.Ordinal)',
    '        );',
    '}',
    '',
  ].join('\n');
}

/** `channel-strip` as `ChannelStrip`, the member name every language derives. */
function memberOf(slot: string): string {
  return slot
    .split('-')
    .map(part => part.charAt(0).toUpperCase() + part.slice(1))
    .join('');
}

/**
 * The slot words on their own, as a C# vocabulary.
 *
 * `PluginSlots` answers whether a pair is known; this answers what the words
 * are. The clients need the words, because packages/design/nm-components reads a
 * `public const string` vocabulary and writes it into TypeScript, Kotlin and
 * Swift. A slot spelled by hand in a client is a placement that silently
 * vanishes on that client alone.
 */
export function emitSlotVocabulary(slots: Slot[]): string {
  const distinct: string[] = [...new Set(slots.map(slot => slot.slot))];
  const kinds: string[] = [...new Set(slots.map(slot => slot.kind))];

  const constants: string[] = distinct.flatMap(slot => [
    `    /// <summary>${slots.find(row => row.slot === slot)?.summary ?? ''}</summary>`,
    `    public const string ${memberOf(slot)} = "${slot}";`,
    '',
  ]);

  const byKind: string[] = kinds.map(kind => {
    const members: string = slots
      .filter(row => row.kind === kind)
      .map(row => memberOf(row.slot))
      .join(', ');

    return `        [PluginKind.${kind.charAt(0).toUpperCase() + kind.slice(1)}] = [${members}],`;
  });

  return [
    LICENSE_HEADER,
    'namespace NoMercy.PluginSdk.Abstractions;',
    '',
    '/// <summary>',
    '/// Where inside a kind a placement lands.',
    '///',
    '/// A plugin says which kind it is and which slot it wants; the client owns the',
    '/// drawing. Without slots every placement was a navigation entry, so a plugin',
    '/// that belonged on the music home page could only add a sidebar link.',
    '/// </summary>',
    'public static class PluginSlot',
    '{',
    ...constants,
    '    public static IReadOnlyList<string> All { get; } =',
    `    [${distinct.map(slot => memberOf(slot)).join(', ')}];`,
    '',
    '    private static readonly Dictionary<string, string[]> ByKind = new()',
    '    {',
    ...byKind,
    '    };',
    '',
    '    /// <summary>The slots this kind may ask for, in the order clients draw them.</summary>',
    '    public static IReadOnlyList<string> For(string kind)',
    '    {',
    '        return ByKind.TryGetValue(kind, out string[]? slots) ? slots : [];',
    '    }',
    '',
    '    /// <summary>Whether this kind can be placed in this slot.</summary>',
    '    public static bool IsValid(string kind, string slot)',
    '    {',
    '        return For(kind).Contains(slot);',
    '    }',
    '}',
    '',
  ].join('\n');
}

/**
 * The analyzer rules, as a C# table.
 *
 * Each rule's message is the sentence the matching refusal already carries, so
 * an author meets one wording in the editor and the same one at run time.
 */
export function emitAnalyzerDescriptors(rules: AnalyzerRule[]): string {
  const rows: string[] = rules.map(
    rule =>
      `        new("${rule.id}", ${JSON.stringify(rule.title)}, ${rule.capability === null ? 'null' : `"${rule.capability}"`}),`,
  );

  return [
    LICENSE_HEADER,
    '// netstandard2.0, so nothing is implicit: an analyzer runs inside Roslyn,',
    '// not inside the server, and that target has no implicit usings.',
    'using System;',
    'using System.Collections.Generic;',
    'using System.Linq;',
    '',
    'namespace NoMercy.PluginSdk.Analyzers;',
    '',
    '/// <summary>One analyzer rule.</summary>',
    '/// <param name="Id">The diagnostic id, NMP0001 upward.</param>',
    '/// <param name="Title">What the author reads, worded as the refusal words it.</param>',
    '/// <param name="Capability">The capability it is about, or null when it is about none.</param>',
    'public sealed record PluginAnalyzerDescriptor(string Id, string Title, string? Capability);',
    '',
    '/// <summary>Every rule this contract declares.</summary>',
    'public static class PluginAnalyzerDescriptors',
    '{',
    '    public static readonly IReadOnlyList<PluginAnalyzerDescriptor> All =',
    '    [',
    ...rows,
    '    ];',
    '',
    '    public static PluginAnalyzerDescriptor ById(string id) =>',
    '        All.Single(descriptor => string.Equals(descriptor.Id, id, StringComparison.Ordinal));',
    '}',
    '',
  ].join('\n');
}
