import type { Capability } from './contract.js';

export function emitCapabilitiesTypescript(capabilities: Capability[]): string {
  const rows: string[] = capabilities.map(capability =>
    `\t'${capability.name}': { scope: '${capability.scope}', trust: '${capability.trust}', reversible: ${capability.reversible}, facade: '${capability.facade}' },`,
  );

  return [
    '// Generated by server/nomercy-media-server/tools/plugin-contract. Do not edit.',
    '',
    'export const PluginCapabilities = {',
    ...rows,
    '} as const;',
    '',
    'export type PluginCapabilityName = keyof typeof PluginCapabilities;',
    "export type PluginCapabilityTrust = 'low' | 'medium' | 'high';",
    '',
  ].join('\n');
}
