import type { Capability } from './contract.js';
import { pascalOf } from './contract.js';

export const LICENSE_HEADER: string = [
  '// -----------------------------------------------------------------------------',
  '//  Copyright (c) 2024-present NoMercy Entertainment. All rights reserved.',
  '//',
  '//  This file is part of NoMercy MediaServer, source-available software (NOT open',
  '//  source). Personal use and contributions are welcome; distribution, resale,',
  '//  relicensing, and commercial exploitation are prohibited without explicit',
  '//  written consent. See LICENSE for full terms. Distributed WITHOUT ANY WARRANTY.',
  '//',
  '//  SPDX-License-Identifier: LicenseRef-NoMercy-Proprietary',
  '// -----------------------------------------------------------------------------',
  '',
  '// Generated by tools/plugin-contract. Do not edit.',
  '',
].join('\n');

function trustOf(capability: Capability): string {
  return capability.trust.charAt(0).toUpperCase() + capability.trust.slice(1);
}

function quote(text: string): string {
  return `"${text.replace(/"/g, '\\"')}"`;
}

function descriptorOf(capability: Capability): string {
  const args: string[] = [
    quote(capability.name),
    quote(capability.scope),
    `PluginTrust.${trustOf(capability)}`,
    `${capability.reversible}`,
    quote(capability.facade),
    quote(capability.summary),
  ];

  return [
    '        new(',
    ...args.map((argument, index) => `            ${argument}${index < args.length - 1 ? ',' : ''}`),
    '        ),',
  ].join('\n');
}

export function emitCapabilityVocabulary(capabilities: Capability[]): string {
  const rows: string[] = capabilities.map(descriptorOf);

  return [
    LICENSE_HEADER,
    'namespace NoMercy.Plugins.Abstractions;',
    '',
    '/// <summary>Every capability a manifest may declare, with its scope, trust floor and facade.</summary>',
    'public static class PluginCapabilityVocabulary',
    '{',
    '    public static IReadOnlyList<PluginCapabilityDescriptor> All { get; } =',
    '    [',
    rows.join('\n'),
    '    ];',
    '',
    '    public static PluginCapabilityDescriptor? ByName(string name)',
    '    {',
    '        return All.FirstOrDefault(capability => capability.Name == name);',
    '    }',
    '}',
    '',
  ].join('\n');
}

export function emitCapabilityNames(capabilities: Capability[]): string {
  const rows: string[] = capabilities.map(
    capability => `    public const string ${pascalOf(capability.name)} = ${quote(capability.name)};`,
  );

  return [
    LICENSE_HEADER,
    'namespace NoMercy.Plugins.Abstractions;',
    '',
    '/// <summary>The capability names, so nothing spells one by hand.</summary>',
    'public static class PluginCapabilityNames',
    '{',
    rows.join('\n'),
    '}',
    '',
  ].join('\n');
}
