/**
 * The fixture set, embedded where each client's test runner can reach it.
 *
 * A test that reads the JSON off disk works on web and in C# and does not work
 * in a Kotlin common test, which has no filesystem. Embedding it means one set
 * of bytes reaches all four, and the drift check catches a client whose copy
 * is stale.
 */
export function emitFixturesTypescript(fixturesJson: string): string {
  return [
    '// Generated by tools/plugin-contract. Do not edit.',
    '//',
    '// One placement per declared slot, and the view the server answers for it.',
    '// Every client renders this same set, so a slot a client draws nowhere',
    '// fails a test instead of looking fine until someone opens that screen.',
    '',
    'export interface PluginFixtureEntry {',
    '\tsection: string;',
    '\tlabel: string;',
    '\ticon: string | null;',
    '\troute: string;',
    '\tslot: string;',
    '\taccess: string;',
    '}',
    '',
    'export interface PluginFixture {',
    '\tkind: string;',
    '\tslot: string;',
    '\twhy: string;',
    '\tentry: PluginFixtureEntry;',
    '\tview: {',
    '\t\tlayout: string;',
    '\t\trefreshInterval: number;',
    '\t\tcomponents: Array<{ id: string; component: string; props: Record<string, unknown> }>;',
    '\t};',
    '}',
    '',
    `export const pluginFixtures = ${fixturesJson.trimEnd()} as unknown as {`,
    '\tplugin: string;',
    '\tfixtures: PluginFixture[];',
    '};',
    '',
  ].join('\n');
}

export function emitFixturesKotlin(fixturesJson: string, packageName: string): string {
  return [
    '// Generated by tools/plugin-contract. Do not edit.',
    '',
    `package ${packageName}`,
    '',
    '/**',
    ' * One placement per declared slot, and the view the server answers for it.',
    ' *',
    ' * Every client renders this same set, so a slot this app draws nowhere fails',
    ' * a test instead of looking fine until someone opens that screen.',
    ' */',
    'object PluginFixtures {',
    '    const val JSON: String = """',
    fixturesJson.trimEnd(),
    '"""',
    '}',
    '',
  ].join('\n');
}
