import { readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';

/**
 * Every component name the kitchen sink actually sends.
 *
 * Read out of the sink payloads rather than typed here. The sink is written by
 * the plugin's own test run, so this list is what a server really puts on the
 * wire, and a client can be asked whether it draws all of it.
 */
export function sinkComponentNames(fixtureDir: string): string[] {
  const names = new Set<string>();

  for (const file of readdirSync(fixtureDir)) {
    if (!file.endsWith('.json')) {
      continue;
    }

    collect(JSON.parse(readFileSync(join(fixtureDir, file), 'utf8')), names);
  }

  return [...names].sort();
}

function collect(node: unknown, names: Set<string>): void {
  if (Array.isArray(node)) {
    for (const one of node) {
      collect(one, names);
    }

    return;
  }

  if (node === null || typeof node !== 'object') {
    return;
  }

  const record = node as Record<string, unknown>;

  if (typeof record.component === 'string') {
    names.add(record.component);
  }

  for (const value of Object.values(record)) {
    collect(value, names);
  }
}

export function emitSinkComponentsTypescript(names: string[]): string {
  return [
    '// Generated by tools/plugin-contract. Do not edit.',
    '//',
    '// Every component name the kitchen sink puts on the wire, read out of the',
    '// payloads the plugin\'s own test run wrote. A client is asked whether it',
    '// draws all of it, so a renderer that falls out of a registry is named here',
    '// rather than silently drawing nothing.',
    '',
    'export const sinkComponents: readonly string[] = [',
    ...names.map(name => `\t'${name}',`),
    '] as const;',
    '',
  ].join('\n');
}
