import type { Capability } from './contract.js';

function constantOf(name: string): string {
  return name.replace(/\./g, '_').toUpperCase();
}

function setOf(label: string, names: string[]): string {
  return [
    `    val ${label}: Set<String> = setOf(`,
    ...names.map(name => `        ${constantOf(name)},`),
    '    )',
  ].join('\n');
}

export function emitCapabilitiesKotlin(capabilities: Capability[], packageName: string): string {
  return [
    '// Generated by tools/plugin-contract. Do not edit.',
    '',
    `package ${packageName}`,
    '',
    '/** Every capability a manifest may declare. The server decides these words. */',
    'object PluginCapabilities {',
    ...capabilities.map(capability => `    const val ${constantOf(capability.name)} = "${capability.name}"`),
    '',
    setOf('ALL', capabilities.map(capability => capability.name)),
    '',
    setOf('MEDIUM', capabilities.filter(capability => capability.trust === 'medium').map(capability => capability.name)),
    '',
    setOf('HIGH', capabilities.filter(capability => capability.trust === 'high').map(capability => capability.name)),
    '',
    setOf('IRREVERSIBLE', capabilities.filter(capability => !capability.reversible).map(capability => capability.name)),
    '}',
    '',
  ].join('\n');
}
