/**
 * The fixture set, embedded where each client's test runner can reach it.
 *
 * A test that reads the JSON off disk works on web and in C# and does not work
 * in a Kotlin common test, which has no filesystem. Embedding it means one set
 * of bytes reaches all four, and the drift check catches a client whose copy
 * is stale.
 */
export function emitFixturesTypescript(fixturesJson: string): string {
  return [
    '// Generated by tools/plugin-contract. Do not edit.',
    '//',
    '// One placement per declared slot, and the view the server answers for it.',
    '// Every client renders this same set, so a slot a client draws nowhere',
    '// fails a test instead of looking fine until someone opens that screen.',
    '',
    'export interface PluginFixtureEntry {',
    '\tsection: string;',
    '\tlabel: string;',
    '\ticon: string | null;',
    '\troute: string;',
    '\tslot: string;',
    '\taccess: string;',
    '}',
    '',
    'export interface PluginFixture {',
    '\tkind: string;',
    '\tslot: string;',
    '\twhy: string;',
    '\tentry: PluginFixtureEntry;',
    '\tview: {',
    '\t\tlayout: string;',
    '\t\trefreshInterval: number;',
    '\t\tcomponents: Array<{ id: string; component: string; props: Record<string, unknown> }>;',
    '\t};',
    '}',
    '',
    `export const pluginFixtures = ${literal(JSON.parse(fixturesJson), 0)} as unknown as {`,
    '\tplugin: string;',
    '\tfixtures: PluginFixture[];',
    '};',
    '',
  ].join('\n');
}

const IDENTIFIER = /^[A-Za-z_$][\w$]*$/;

/**
 * The same data as a TypeScript literal, in the style both apps lint for.
 *
 * Pasted in as JSON it is double-quoted and space-indented, and the receiver's
 * lint step failed on the generated file rather than on anything anybody wrote.
 */
function literal(value: unknown, depth: number): string {
  const pad = '\t'.repeat(depth + 1);
  const close = '\t'.repeat(depth);

  if (value === null) {
    return 'null';
  }

  if (Array.isArray(value)) {
    if (value.length === 0) {
      return '[]';
    }

    return `[\n${value.map(one => `${pad}${literal(one, depth + 1)},`).join('\n')}\n${close}]`;
  }

  if (typeof value === 'object') {
    const entries = Object.entries(value as Record<string, unknown>);

    if (entries.length === 0) {
      return '{}';
    }

    const rows = entries
      .map(([name, one]) => `${pad}${key(name)}: ${literal(one, depth + 1)},`)
      .join('\n');

    return `{\n${rows}\n${close}}`;
  }

  if (typeof value === 'string') {
    return `'${value.replace(/\\/g, '\\\\').replace(/'/g, "\\'").replace(/\n/g, '\\n')}'`;
  }

  return String(value);
}

function key(name: string): string {
  return IDENTIFIER.test(name) ? name : `'${name.replace(/'/g, "\\'")}'`;
}

export function emitFixturesKotlin(fixturesJson: string, packageName: string): string {
  return [
    '// Generated by tools/plugin-contract. Do not edit.',
    '',
    `package ${packageName}`,
    '',
    '/**',
    ' * One placement per declared slot, and the view the server answers for it.',
    ' *',
    ' * Every client renders this same set, so a slot this app draws nowhere fails',
    ' * a test instead of looking fine until someone opens that screen.',
    ' */',
    'object PluginFixtures {',
    '    const val JSON: String = """',
    fixturesJson.trimEnd(),
    '"""',
    '}',
    '',
  ].join('\n');
}
